name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: typechain
          path: typechain
      - run: npm test
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          name: codecov-umbrella
          fail_ci_if_error: true
          flags: unittests
